### PR TITLE
Port the translation functions from shared auth

### LINKED ISSUE #15: Add language formatting functions
#### Describe the desired behavior
Add the language formatting functions that were removed from react-auth-shared

#### Describe the current behavior
No functions.

#### Is this request related to a current issue?
We're removing the dependency on highcharts from the auth workflows

### PR DESCRIPTION
**Pull request by joebochill**
Fixes #15 

#### Changes proposed in this Pull Request:
- Move language formatting functions from react-auth-shared
- Update readme with usage instructions
- Update dependencies
- Export all utilities from root file

### CODE REVIEW

**Comment by jeffvg** [comment]
trying to run the angular high charts demo, seeing this

* ERROR in node_modules/@pxblue/highcharts/dist/utilities/i18n.d.ts:3:94 - error TS2694: Namespace '"/Users/e0458886/pxblue/highcharts/angular-demo/node_modules/highcharts/highcharts"' has no exported member 'AxisDateTimeLabelFormatsOptions'.

* 3 export declare const getChartsAxisDateTimeLabelFormats: (i18nLanguage: string) => Highcharts.AxisDateTimeLabelFormatsOptions | undefined

**Comment by joebochill** [comment]
Good catch...I'm rescaffolding the demo projects now. The angular one was still using Angular 8!

**Comment by jeffvg** [comment]
we have several tests failing now. The react one is not finding text via screen.getByText anymore. I tried using getByAltText but had same results.

TestingLibraryElementError: Unable to find an element with the text: /PX Blue/i.

test('renders learn react link', () => {
    render(<App />);
    const pxbText = screen.getByText(/PX Blue/i);
    expect(pxbText).toBeInTheDocument();
});

**Review by jeffvg — APPROVED** [review]
all good now

**Pull request merged**
